### ISSUE TITLE
RuntimeError: unknown Entity type "Project"

### ISSUE THREAD

**Issue by Kif11** [ndunsworth/python-shotgunorm#27]
Hi Nathan,

Try to do I first run on this ORM

```python
import modules.sgorm as sgorm

URL = 'https://aaa.shotgunstudio.com'
SCRIPT = 'util'
KEY = 'cf1e303123ca444c73ae421389f596410f23390423423a21d6213234234daf'

sg = sgorm.SgConnection(URL, SCRIPT, KEY)

searchResult = sg.findOne('Project', [['id', 'is', 435]])
```

Getting this error:

```
RuntimeError: unknown Entity type "Project"
```

I see that the *_classCache* gets populated inside of *build* function but I can not quite understand where this function runs because it is not in the __init__. 
```
    newClassCache[entityTypeName] = newEntityClass

        if entityInfo.isCustom():
          self._classCache[entityTypeLabel] = newEntityClass
```

Kirill

**Comment by Kif11** [comment]
Here is my python shell session with a different error:

```
>>> import sys
>>> sys.path.append('/Users/kif/Downloads/python-shotgunorm-master')
>>> import ShotgunORM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kif/Downloads/python-shotgunorm-master/ShotgunORM/__init__.py", line 205, in <module>
    raise ImportError('ShotgunORM unable to find Shotgun Python API module "%s", check "./ShotgunORM/__init__.SHOTGUNAPI_NAME" or sys.path' % config.SHOTGUNAPI_NAME)
ImportError: ShotgunORM unable to find Shotgun Python API module "shotgun_api3", check "./ShotgunORM/__init__.SHOTGUNAPI_NAME" or sys.path
>>> sys.path.append('/Users/kif/Desktop/sg_orm/modules/shotgun_api3')
>>> import ShotgunORM
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kif/Downloads/python-shotgunorm-master/ShotgunORM/__init__.py", line 153, in <module>
    del SgScriptEngine
NameError: name 'SgScriptEngine' is not defined
>>> import ShotgunORM
>>> sg = ShotgunORM.SgConnection('https://aaa.shotgunstudio.com', 'util', 'cf1e303b918f7c432342342342396410f25690a41ba21d6211797d1daf')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kif/Downloads/python-shotgunorm-master/ShotgunORM/SgConnection.py", line 61, in __call__
    result = super(SgConnectionMeta, cls).__call__(*args, **kwargs)
  File "/Users/kif/Downloads/python-shotgunorm-master/ShotgunORM/SgConnection.py", line 387, in __init__
    super(SgConnection, self).__init__(url, login, key)
  File "/Users/kif/Downloads/python-shotgunorm-master/ShotgunORM/SgConnection.py", line 150, in __init__
    self._connection = ShotgunORM.SHOTGUN_API.shotgun.Shotgun(
AttributeError: 'NoneType' object has no attribute 'shotgun'
```

**Comment by ndunsworth** [comment]
Looks like you don't have the official Shotgun api.  The ShotgunORM is a wrapper around the official Python module.

Do you have the official Shotgun api installed?

**Comment by Kif11** [comment]
I downloaded it and I appended it to my sys.path as you can see here:

```
sys.path.append('/Users/kif/Desktop/sg_orm/modules/shotgun_api3')
```

**Comment by ndunsworth** [comment]
You should not include "shotgun_api3" when appending to sys.path.

```
sys.path.append('/Users/kif/Desktop/sg_orm/modules')
```

**Comment by Kif11** [comment]
Well this fix the shotgun attribute error however I'm still getting:

```
  File "/Users/kif/Desktop/sg_orm/modules/sgorm/ShotgunORM/SgEntityClassFactory.py", line 162, in createEntity
    raise RuntimeError('unknown Entity type "%s"' % sgEntityType)
RuntimeError: unknown Entity type "Project"
```
Mentioned in the first message.
